{
 "title": "ESP32 Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Sensor-01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ESP1 Temp Sensor",
   "type": "timeseries",
   "description": "ESP1 temperature sensor with average trendline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(recorded_at),\r\n  (temperature_c * 9.0/5.0 + 32) as temperature_f\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\norder by recorded_at\r\n"
    },
    {
     "rawSql": "select\r\n  date_trunc('day', recorded_at) + interval '4 hours' * floor(extract(hour from recorded_at) / 4) + interval '2 hours' as time,\r\n  avg(temperature_c * 9.0/5.0 + 32) as avg_temperature_f\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\n  and $__timeFilter(recorded_at)\r\ngroup by date_trunc('day', recorded_at), floor(extract(hour from recorded_at) / 4)\r\norder by time\r\n"
    }
   ]
  },
  {
   "title": "Humidity %",
   "type": "timeseries",
   "description": "ESP1 humidity sensor with average trendline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(recorded_at),\r\n  humidity_rh as \"Humidity (%)\"\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\norder by recorded_at\r\n"
    },
    {
     "rawSql": "select\r\n  date_trunc('day', recorded_at) + interval '4 hours' * floor(extract(hour from recorded_at) / 4) + interval '2 hours' as time,\r\n  avg(humidity_rh) as avg_humidity_rh\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\n  and $__timeFilter(recorded_at)\r\ngroup by date_trunc('day', recorded_at), floor(extract(hour from recorded_at) / 4)\r\norder by time\r\n"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "description": "ESP1 pressure sensor with average trendline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(recorded_at),\r\n  pressure_hpa as \"Pressure (hPa)\"\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\norder by recorded_at\r\n"
    },
    {
     "rawSql": "select\r\n  date_trunc('day', recorded_at) + interval '4 hours' * floor(extract(hour from recorded_at) / 4) + interval '2 hours' as time,\r\n  avg(pressure_hpa) as avg_pressure_hpa\r\nfrom public.readings\r\nwhere device_id = 'esp32-lab-01'\r\n  and $__timeFilter(recorded_at)\r\ngroup by date_trunc('day', recorded_at), floor(extract(hour from recorded_at) / 4)\r\norder by time\r\n"
    }
   ]
  }
 ]
}